### ISSUE TITLE
Should add OSGi metadata to JParsec

### ISSUE THREAD

**Issue by srs** [jparsec/jparsec#37]
It would be really useful to make JParsec OSGi compliant out-of-the-box. I can help with this if it's something that you would consider.

Thanks.

**Comment by abailly** [comment]
Please go ahead if you know how to do this quickly. I would gladly merge a PR that helps integrate jparsec into various contexts.

**Comment by gssiyankai** [comment]
JParsec has a runtime dependency on cglib-nodep (and that's the only one) that is not OSGi compliant.
You might have to use the cglib bundle wrapper from Apache ServiceMix.

**Comment by fluentfuture** [comment]
I think we should soon deprecate the classes that use cglib. They brought some convenience in pre-Java8 code. But now that Java 8 is here, their days are gone.

**Comment by almibe** [comment]
Hi all, I've done some work on this issue today and after playing around a bit I believe my fork of jparsec is handling OSGi correctly using the ServiceMix version of cglib.  At first I tried to just remove cglib entirely along with the misc package, but that would require quite a bit of rewriting to get the examples working again.  I think it is possible to remove cglib and still keep misc but that would require a fair amount of work to do.  The other alternative would be too get rid of cglib and rewrite either misc or jparsec itself to play better with idiomatic Java 8 but again that's quite a bit of work.

It'd be cool to get an OSGi friendly version of jparsec out there, so let me know what you think.

**Comment by abailly** [comment]
+1 

I definitely think having a Java 8 *and* OSGi compliant jparsec version would be a great leap forward and certainly warrant a 3.0 version. I have already commented on your PR which breaks CI. Do you have ideas about how involved it would be to move code to Java 8? It's been a while since I have worked seriously  on and with jparsec, so not really sure...

**Comment by fluentfuture** [comment]
In Java 8, I think we can just get rid of the misc package altogether. It was nothing more than a poor-man's lambda.

Not sure if there are other Java 8 goodies we could take advantage of?

(I suspect we could deprecate Map, Map2 and use java.util.Function and BiFunction. But the value seems pretty limited)
