### ISSUE TITLE
Register JParsec at Coveralls

### ISSUE THREAD

**Issue by gssiyankai** [jparsec/jparsec#38]
Hi @abailly and @fluentfuture,
I would like to have continuous feedback on code coverage when I'm contributing to jparsec. I've seen Coveralls is offering this service with a smooth integration with Travis.
So, if you think it might be a good idea to have code coverage, can you please register jparsec at [Coveralls](https://coveralls.io/) ? I would have done it myself but I'm no longer in the collaborators list after the repo has been moved to the jparsec organization.
I'll then take care of the rest in a PR.
Thanks.

**Comment by abailly** [comment]
Hi Greg,
Invited you to be part 'core' team, please confirm in issue you've got
rights to do what you request. DEfinitely a good idea.

-- 
Arnaud Bailly

twitter: abailly
skype: arnaud-bailly
linkedin: http://fr.linkedin.com/in/arnaudbailly/

**Comment by gssiyankai** [comment]
Hi Arnaud,
Thank you for the invitation.
Unfortunately, I don't have the rights to register jparsec at Coveralls. I guess only the 'owners' team has the right to do so.

**Comment by abailly** [comment]
Apologies for handling this issue only now. For some unknown reason I cannot see jparsec's repositories on https://coveralls.io/repos so I cannot add them. Any idea why it could be so? I can see all other projects I own or from organisations I am part of but not those ones :-(

**Comment by gssiyankai** [comment]
Hi Arnaud,
Thanks for the feedback. I just managed to register jparsec's repo! The problem was due to the fact that I did not make my membership to jparsec organization public, so coveralls was not able to see the repo.
I'll be working on the remaining tasks soon.

**Comment by abailly** [comment]
Cool! So I must have encountered same issue...

Thanks for your work!

Regards
Arnaud

Le jeudi 30 avril 2015, Gregory SSI-YAN-KAI <notifications@github.com> a
écrit :

> Hi Arnaud,
> Thanks for the feedback. I just managed to register jparsec's repo! The
> problem was due to the fact that I did not make my membership to jparsec
> organization public, so coveralls was not able to see the repo.
> I'll be working on the remaining tasks soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jparsec/jparsec/issues/38#issuecomment-97839466>.
>


-- 
-- 
Arnaud Bailly

twitter: abailly
skype: arnaud-bailly
linkedin: http://fr.linkedin.com/in/arnaudbailly/

**Comment by gssiyankai** [comment]
Hi Arnaud,
Can you add the 'jparsec' repo to the 'core' team ? I don't seem to be allowed to push changes...

**Comment by abailly** [comment]
Looks like on needs to pay something for using coveralls, was not able to figure out how it works.
