### ISSUE TITLE
Get unexpected Nested array (version 2.3-SNAPSHOT)

### ISSUE THREAD

**Issue by tangjwt** [jparsec/jparsec#40]
I'm parse some string like : { a { b } } ,
when use lazy  like below:

Parser.Reference<List<String>> ref = Parser.newReference();
		Parser<List<String>> lazy = ref.lazy();
		Parser<String> statement = new Mapper<String>() {
			@SuppressWarnings("unused")
			String map(String filterPath, List<String> expects, int end) {
				System.out.println(expects.size);
				return "";
			}
		}.sequence(Mapper.skip(TerminalParser.terms.token("{"), lazy.many(), Mapper.skip(TerminalParser.terms.token("}")), Parsers.INDEX);
		Parser<List<String>> parse = Parsers.or(string, statement).many1();
		ref.set(parse);

As expect :
List<String> expects value is :[a,b]

but actual is [[a,b]], 

added useless Nested array.

**Comment by fluentfuture** [comment]
It looks like the sequence call expects two single parameters: the list and
the index; while the mapper signature wants 3 parameters?

**Comment by tangjwt** [comment]
Sorry , my fault , I delete some unrelated code,but didn't check.

Runnable code is :

	static Parser<List<String>> statement() {
		Parser.Reference<List<String>> ref = Parser.newReference();
		Parser<List<String>> lazy = ref.lazy();
		Parser<String> statement = new Mapper<String>() {
			@SuppressWarnings("unused")
			String map(List expects, int end) {
				System.out.println(expects);
				return "";
			}
		}.sequence(Mapper.skip(terms.token("{")), lazy.many(), Mapper.skip(terms.token("}")), Parsers.INDEX);
		Parser<List<String>> parse = Parsers.or(Terminals.Identifier.PARSER, statement).many1();
		ref.set(parse);
		return parse;
	}
	static final Terminals terms = Terminals.operators("{", "}").words(Scanners.IDENTIFIER).build();

simple test code:

statement().from(Parsers.or(terms.tokenizer()), Scanners.JAVA_DELIMITER.skipMany()).parse("{abc}");

output is :
[[abc]]

**Comment by fluentfuture** [comment]
The lazy parser's type is List, calling many() on it will make it List of
List.

**Comment by tangjwt** [comment]
Thank you for correcting me .
By the way , I want to know, Is there has a simple way to get  current line number and  column number rather than index?

**Comment by fluentfuture** [comment]
No. You will have to figure out the line number yourself.

Sorry.

**Comment by tangjwt** [comment]
I see. Thanks anyway.
