### ISSUE TITLE
Can you package current git codes to marven?

### ISSUE THREAD

**Issue by jingtaozf** [jparsec/jparsec#41]
Hi,dev:

Can you public to current git codes to marven, I need to use it in jdk 1.8.

Thanks.:)

With Best Regards,
jingtao.

**Comment by abailly** [comment]
Done as part of release 2.3.

**Comment by jingtaozf** [comment]
I am sorry but I can't find jparsec 2.3 in maven:
https://repo1.maven.org/maven2/jparsec/jparsec/

Did I missed something?

**Comment by abailly** [comment]
It seems I forgot to release from staging... Will do that.
