### ISSUE TITLE
ParseErrorDetails not correct for partially parsed string

### ISSUE THREAD

**Issue by tobiasrodehutskors** [jparsec/jparsec#44]
If I execute the following code:

```java
    @Test
    public void test() {
        Scanners.string("tasks").parse("tas");
    }
```

I get the this error:

> org.codehaus.jparsec.error.ParserException: line 1, column 1:
> tasks expected, t encountered.

But I expected it to look like this:

> org.codehaus.jparsec.error.ParserException: line 1, column 3:
> tasks expected, tas encountered.

Is this a bug or am I missing something?

**Comment by fluentfuture** [comment]
Yes. There are two modes for a Parser: character-mode and token-mode.

In character mode, all the Parser sees are characters so it won't know to
report "tas", nor will it know that it's supposed to only report the next
"word", which is comprised of alphanumeric characters, excluding
whitespaces and punctuations, as opposed to reporting the entire remaining
text that could be huge.

At token level, however, the parser will be able to see each token as an
atomic input. But it requires a bit more work to define tokens
<http://jparsec.github.io/jparsec/apidocs/org/codehaus/jparsec/Terminals.html>
and then connect
<http://jparsec.github.io/jparsec/apidocs/org/codehaus/jparsec/Parser.html#from(org.codehaus.jparsec.Parser)>
char-level scanners with token-level parsers. You can also check out the
example code in the tutorial
<https://github.com/jparsec/jparsec/wiki/Tutorial> to see how tokens are
used.

Cheers,

**Comment by abailly** [comment]
Not a bug
