### ISSUE TITLE
Add release to maven central

### ISSUE THREAD

**Issue by jandk** [jparsec/jparsec#46]
As you could infer from the title, it would be nice if we could use the latest version from maven central

**Comment by abailly** [comment]
I thought I had done it :(

**Comment by jandk** [comment]
http://mvnrepository.com/artifact/org.jparsec/jparsec

Nope ;)

**Comment by abailly** [comment]
I will do it !

**Comment by jandk** [comment]
Awesome!

**Comment by abailly** [comment]
Should be ok now or in a few hours, depending on speed of propagation to maven central
