### ISSUE TITLE
A simple example is needed

### ISSUE THREAD

**Issue by ianrae** [jparsec/jparsec#49]
I am neither a Haskell programmer or a compiler writer and found learning jparsec to be a challenge. The examples jump from a basic calculator to complex things like BNF and SQL.  There needs to be an in-between sample.  So I wrote one and it is at https://github.com/ianrae/simplejparsec.   I probably have some terminology wrong.  Comments are welcome.

**Comment by abailly** [comment]
Would you consider providing a PR to jparsec project?

**Comment by ianrae** [comment]
Sure.  They are self-contained unit tests.  I'm pretty sure I am not using the API in the best way though.  For example I use Parser.or when I am parsing only one item; there is probably a better way :)

**Comment by abailly** [comment]
Sure. I think that providing  a PR would allow @fluentfuture and I to provide more precise feedback, suggest improvements and maybe upgrade part of the wiki/documentation to help other people learn jparsec based on your experience.

**Comment by ianrae** [comment]
OK.  I may add some of the feedback into my content because learning is often aided by 
  a) learn simple ways to get the job done
  b) learn how to improve on (a)

Both can be valuable for people to see.

**Comment by abailly** [comment]
👍

**Comment by ianrae** [comment]
I cloned jparsec, created a branch, and then used the Pull Request button in Github desktop to create a PR.  But it is failing due to permissions i think.  Is there another way I should be creating a PR?  Thanks.

**Comment by abailly** [comment]
You might not be creating the PR with the right branches. Be sure to select "Create PR across forks": You don't need special rights on the repository to create a PR, only to merge it. HTH.

**Comment by fluentfuture** [comment]
PR merged.
