### ISSUE TITLE
Release jparsec 3.0 with Java 8 Support

### ISSUE THREAD

**Issue by fluentfuture** [jparsec/jparsec#51]
May be time to pull the trigger.

Anything we also want to make sure to get into this release?

**Comment by abailly** [comment]
I would like to change the copyright and maybe the packages name.

**Comment by scolomer** [comment]
Hello,

I've made some modification in my fork of jparsec, if you are interested I can issue merge requests for some of them:
- Java 8 support: added @FunctionalInterface to TokenMap and Map[n] (d12d0d87dc72aebd97a63ca0d71b59fcc22ef191), added a map method to Pair and Tuple[n] (e6adba3901e0c272999084862ee430f46a05f86b).
Now my parses look like : 
```java
sequence(token("while").next(EXPRESSION.between(token("("), token(")"))), BLOCK.followedBy(token("end")),(a, b) -> new WhileStatement(a, b))
```
or
```java
tuple(token("while").next(EXPRESSION.between(token("("), token(")"))), BLOCK.followedBy(token("end"))).map(a -> new WhileStatement(a.a, a.b))
```
- position combinator to evaluate a parser only for a specified position (357c64f2c8a4c442e685486ad82eba3799c26c83).
- Parser<Token> ANY_TOKEN2, just like ANY_TOKEN, but returns the token instead of the token value (7041da11f65b2f1e1f85f63e0092d4ac745dbe4a).

**Comment by fluentfuture** [comment]
@scolomer The Map[n] interfaces are already marked as @FunctionalInterface. I didn't do so for TokenMap because I think it's very specialized and much less frequently used interface. So seeing the actual type (TokenMap) may be helpful to code readers (unlike the Map[n] interfaces).

Pair and Tuple[n] are being deprecated. In Java 8, it's easy enough to create one's own value object and use map() to transform, so there is less utility in these semantic-less value objects.

**Comment by almibe** [comment]
It would be nice to get "codehaus" out of the package structure.  Especially since the group id for the project is just "org.jparsec" and not "org.codehaus.jparsec".

(I'm assuming this is what @abailly was mentioning)

**Comment by abailly** [comment]
Yes, that's what I suggested. Will take care if that this weekend as well
as double checking copyright and will update PRs.

Le 3 déc. 2016 04:38, "Alex Michael Berry" <notifications@github.com> a
écrit :

**Comment by abailly** [comment]
Update PR #52 and #48. Would appreciate a second pair of eyes to check this...

**Comment by abailly** [comment]
Need to update `README.md` then we'll be ready to release 3.0 !

**Comment by scolomer** [comment]
Sorry, I didn't see your commit with @FunctionalInterface...

For TokenMap, I use it where I could have use a simple Parser.map(), probably bad habits that persists. I agreen there's non need for @FunctionalInterface.

For tuples I prefer writing `tuple(p1, p2, ... ).map(a -> ...)` than `sequence(p1,p2, a -> m)`, but there's no real difference.
Still i think tuple can be usefull to break complex parser into smaller ones where there's no need to create an object.

**Comment by Locke** [comment]
> Need to update `README.md` then we'll be ready to release 3.0 !

Is it possible to publish a RC before a final release, so that users can try that out without building jparsec for them self?

**Comment by abailly** [comment]
Released 3.0-rc1
Will release 3.0 final next week unless some issue pops up

**Comment by Locke** [comment]
Thanks for the RC. If someone else has problems finding it: I had to explicitly enable the "orgjparsec-1010" sonatype repo as it was in neither public/releases/snapshots. I'm using sbt / scala so I don't know if/how this applies to maven users.

After renaming the imports everything still worked fine, so migration should be very easy for everyone.

I adapted some of my parsers to the new Java 8 style and really like the shorter notation :)

**Comment by abailly** [comment]
Forgot to release repo on sonatype... Will never be able to do it right the first time, I guess :(

**Comment by abailly** [comment]
Going to release 3.0 final...

-- 
Arnaud Bailly

twitter: abailly
skype: arnaud-bailly
linkedin: http://fr.linkedin.com/in/arnaudbailly/

**Comment by abailly** [comment]
Done
