### ISSUE TITLE
Calculator Tutorial does not compile as is

### ISSUE THREAD

**Issue by JohnMcGuinness** [jparsec/jparsec#58]
If you copy the Calculator class from the bottom of the tutorial page it does not compile.

```BinaryOperator.MUL``` causes a compilation error in

```
static final Parser<BinaryOperator> WHITESPACE_MUL = 
  term("+", "-", "*", "/").not().retn(BinaryOperator.MUL);
```

I assume ```BinaryOperator``` is ```java.util.function.BinaryOperator``` but because imports are not included in the sample code I cannot be sure.

**Comment by fluentfuture** [comment]
Thanks for the heads up! Should be fixed now.
