### ISSUE TITLE
Some wiki links to java classes are incorrect

### ISSUE THREAD

**Issue by Otaka** [jparsec/jparsec#59]
On the page https://github.com/jparsec/jparsec/wiki/Overview(and may be on others) there are links 
https://github.com/abailly/jparsec/blob/master/jparsec/src/main/java/org/codehaus/jparsec/Parser.java
https://github.com/abailly/jparsec/blob/master/jparsec/src/main/java/org/codehaus/jparsec/Scanners.java
...
and they lead to the 404 page

**Comment by abailly** [comment]
Thanks for reporting! We changed the package but I forgot to update wiki
links.
