### ISSUE TITLE
Add a LOCATION conveniance parser

### ISSUE THREAD

**Issue by bonastos** [jparsec/jparsec#62]
I propose to add a static parser named LOCATION to Parsers, similar to the INDEX parser.

This does not add any new functionality to jparsec, But it would, IMHO, enhance the usability.

The location information can be recomputed using the source string and the index returned by the INDEX parser. But doing so is not really trivial. I mention SourceLocator as an example.

Also , from my own experience, I was a little frustrated when I realized that the functionality must exist within jparsec and there's no way to access it. So I looked into the source, found SourceLocator and copied it. But it still feels dirty to have to do it,

I think any user who's interested in line/offset information would appreciate having a LOCATION parser instead of doing the work himself..

There are alternatives how to help the user with location information,
- Make SourceLoacator public. A user won't have to reinvent the wheel. To me this option is a mismatch with the jparsec philosophy to provide functionality as a parser.
- Make ParseContext public. A user can just write his own location parser. This option opens many cans of worms that should maybe better be left unopened ...

**Comment by fluentfuture** [comment]
I think API-wise, it makes perfect sense. The reason LOCATION hasn't been added is for efficiency.

JParsec's evaluation is eager. Each time it tries a parser object, the value is evaluated, and when parser backtracks, the previously evaluated values are discarded.

This however doesn't perfectly align with SourceLocator, which is slower than O(1). At time of constructing the parser exception, this is fine because we do it just once.

But to be able to compute the location all the time as the parser advances the cursor or backtracks, a more efficient implementation may be needed.

**Comment by fluentfuture** [comment]
One possibility is maybe to make the `Location` class an interface, and then create a lazy implementation of it.

This way merely constructing Location object at backtrack won't be expensive. 

Although, I'm not super confident about the performance difference difference. SourceLocator uses binary search so it may not be all that bad. If you have some time to do some benchmarking that'd be super useful for us to decide whether it's worth it to pull the lazy-calculation trick.

**Comment by bonastos** [comment]
OK, I'll give it a try.

**Comment by fluentfuture** [comment]
Thanks for doing the benchmark!

Given that parsers with backtracking could be negatively impacted by LOCATION, I wonder if we should implement a lazy Location parser?

For example, we could add a SourceIndex class as such:
```java
public final SourceIndex {
  private final int index;
  private final SourceLocator locator;
  private Location location;

  public int getIndex() {
    return index;
  }

  // call it only after the parser has succeeded.
  public synchronized Location getLocation() {
    if (location == null) location = locator.locate(index);
    return location;
  }
}
```

Once we have it, we can deprecate `INDEX` parser, and add `public static final Parser<SourceIndex> SOURCE_INDEX` as the new way to get either the index or the location and perhaps even more functionalities, such as the tokens before and after it if we need them.

**Comment by bonastos** [comment]
An unrelated observation: The snapshot javadoc is not available at the moment,

**Comment by fluentfuture** [comment]
Fixed javadoc.

Added SOURCE_LOCATION parser. Please give it a try and let me know what I may be missing?

Thanks!

**Comment by bonastos** [comment]
Performance is within measurement error of INDEX parser.
I'd call it a good job :-)
