### ISSUE TITLE
Potential Performance Problem with String Source & Regex Parser

### ISSUE THREAD

**Issue by bonastos** [jparsec/jparsec#63]
When I started using Jparsec I encountered the following situation:

I read a 600kB file into a String. Parsing took more than 3.5s. A profiler showed  that almost all time was spent below the DOUBLE_QUOTE_STRING parser. The used regex parser actually calls subSequence on the source CharSequence to call the Java Regex. With the String source this resulted in the creation of about 8000 300kB string instances. 

I changed my input to read into a CharBuffer, and parsing time dropped below 0.3 s. (Same parser)

I don't think any action is required here. But the problem could be an entry for the GOTCHA section.

**Comment by fluentfuture** [comment]
Perhaps we should replace regex with something lightweight. For example, DOUBLE_QUOTE_STRING can likely be implemented using `Pattern`, or with
```
Parsers.between(
        Scanners.isChar('"'),
        Scanners.notChar('"').or(Scanners.string("\\\\").or(Scanners.string("\\\"")),
        Scanners.isChar('"'))
    .source();
```

I didn't test it but something like that possibly will work.

I didn't want to do this micro-optimization until I have a benchmark. Do you think you could add a benchmark of this parser so we can optimize with something to guide us?

**Comment by bonastos** [comment]
Something like  this would solve the problem for DOUBLE_QUOTE_STRING. (And it would be interesting to measure the performance difference,)

But the observation I actually wanted to make is that any parser Constructed from Patterns.regex has this potential problem  when used with a string as source.

As I don't see a general solution (regex matching always starts at position 0 in the passed Charsequence), this still remains a GOTCHA that should be mentioned.

**Comment by fluentfuture** [comment]
Agreed. Do you think a note in the javadoc of `Patterns.regex()` addresses the problem?

**Comment by fluentfuture** [comment]
Changed javadoc and also changed DOUBLE_QUOTE_STRING to manual Pattern.

**Comment by bonastos** [comment]
Looking good to me.
Thanks again for your support and patience.
