### ISSUE TITLE
Remove unnecessary dependecy org.apache.servicemix.bundles:org.apache.servicemix.bundles.cglib

### ISSUE THREAD

**Issue by rserra** [jparsec/jparsec#65]
In order to eliminate unnecessary dependency, the org.apache.servicemix.bundles:org.apache.servicemix.bundles.cglib must be removed. This brings problems in osgi containers since it requires this dependency and the dependencies that the latter includes.

**Comment by fluentfuture** [comment]
I have removed cglib dependency.
