### ISSUE TITLE
Review copyright ownership

### ISSUE THREAD

**Issue by abailly** [jparsec/jparsec#8]
Current copyright owner for jparsec is Codehaus. Is this still relevant and appropriate? Given project has moved to github, why would codehaus retain copyright on it? If not can we change it and for whom/which organization? 

jparsec2.0's license is Apache 2.0 which is liberal and maximizes probability of reuse, so it feels ok to stick with it.

**Comment by dmg46664** [comment]
I don't understand the response from Codehaus as it references itself.

Can the history of the project in terms of copyright be clarified?

The opening statement of this issue suggests that the project is Apache 2.0 License, but I don't see that anywhere in the code.

**Comment by fluentfuture** [comment]
Yes. It is meant to be Apache 2.0. Patch is welcome to apply the license
info to code.
